import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

live_config_reload = true

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.97
padding = {x = 0, y = 0}


[font]
size = 15

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"


[shell]
program = "/bin/zsh"