#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#0c7bbb'
    leading_diamond = '╭─'
    template = ' {{ if .WSL }} on {{ end }}{{ .Icon }}  '

    [blocks.segments.properties]
      alpine = ''
      arch = ''
      centos = ''
      debian = ''
      elementary = ''
      fedora = ''
      gentoo = ''
      linux = ''
      macos = ''
      manjaro = ''
      mint = ''
      opensuse = ''
      raspbian = ''
      ubuntu = ''
      windows = ''

  [[blocks.segments]]
    type = 'text'
    style = 'diamond'
    powerline_symbol = ''
    foreground = '#ffffff'
    background = '#DA627D'
    template = ' 🏠  '

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#ffffff'
    background = '#8a62da'
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#43CCEA'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}', '{{ if gt .Ahead 0 }}#B388FF{{ end }}', '{{ if gt .Behind 0 }}#B388FF{{ end }}']
    background = '#191f48'
    trailing_diamond = ''
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      branch_max_length = 25.0
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'sysinfo'
    style = 'diamond'
    foreground = '#81ff91'
    template = '<#cc7eda> | </><#7eb8da>RAM:</> {{ (div ((sub .PhysicalTotalMemory .PhysicalFreeMemory)|float64) 1073741824.0) }}/{{ (div .PhysicalTotalMemory 1073741824.0) }}GB'

  [[blocks.segments]]
    type = 'node'
    style = 'powerline'
    foreground = '#81ff91'
    template = '<#cc7eda> | </><#7eb8da></> {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}'

    [blocks.segments.properties]
      fetch_version = true

  [[blocks.segments]]
    type = 'php'
    style = 'powerline'
    foreground = '#81ff91'
    template = '<#cc7eda> | </><#7eb8da></> {{ .Full }}'

  [[blocks.segments]]
    type = 'npm'
    style = 'powerline'
    foreground = '#81ff91'
    template = '<#cc7eda> | </><#7eb8da> </> {{ .Full }}'

  [[blocks.segments]]
    type = 'sysinfo'
    style = 'powerline'
    foreground = '#81ff91'
    template = '<> </>'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'diamond'
    foreground = '#4b4b4b'
    background = '#cecece'
    leading_diamond = ''
    trailing_diamond = ''
    template = '⌛  {{ .FormattedMs }} '

    [blocks.segments.properties]
      style = 'austin'
      threshold = 150.0

  [[blocks.segments]]
    type = 'time'
    style = 'diamond'
    foreground = '#4b4b4b'
    background = '#cecece'
    leading_diamond = ''
    trailing_diamond = ''
    template = '⏰  {{ .CurrentDate | date .Format }} '

    [blocks.segments.properties]
      time_format = '15:04:05'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#0c7bbb'
    template = '╰─'
